
version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: |
          docker build -t jessecarl/portfolio-images .

workflows:
  version: 2
  build:
    jobs:
      - build
